name: hola-mundo

on:
    workflow_dispatch:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    holaMundo:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: Saludar
              run: node index.js
